import { writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'
import { performance } from 'node:perf_hooks'
import { ImageFilterStore } from '../image-filter/ImageFilter'

type Scenario = {
  tags: string[]
  root?: string
  label: string
}

const DATASET_SIZE = 100_000
const TAG_POOL = [
  'cat',
  'dog',
  'bird',
  'sunset',
  'portrait',
  'landscape',
  'indoor',
  'outdoor',
  'studio',
  'macro',
  'urban',
  'nature',
]
const ROOT_POOL = ['alpha', 'beta', 'gamma', 'delta']

function randomPick<T>(items: T[], rng: () => number): T {
  return items[Math.floor(rng() * items.length)]
}

function createRng(seed: number): () => number {
  let value = seed % 2147483647
  return () => {
    value = (value * 48271) % 2147483647
    return (value - 1) / 2147483646
  }
}

function buildStore(): ImageFilterStore {
  const store = new ImageFilterStore()
  const rng = createRng(42)

  for (let i = 0; i < DATASET_SIZE; i++) {
    const id = `img-${i.toString().padStart(5, '0')}`
    const tagCount = 2 + Math.floor(rng() * 3) // 2–4 tags
    const tags = new Set<string>()
    while (tags.size < tagCount) {
      tags.add(randomPick(TAG_POOL, rng))
    }
    const root = rng() > 0.1 ? randomPick(ROOT_POOL, rng) : undefined
    store.addImage({ id, tags: Array.from(tags), root, path: `${id}.png` })
  }

  return store
}

function runScenario(store: ImageFilterStore, scenario: Scenario, runs: number) {
  const durations: number[] = []
  let totalResults = 0
  for (let i = 0; i < runs; i++) {
    const { results, metrics } = store.filterWithMetrics(scenario.tags, scenario.root)
    durations.push(metrics.durationMs)
    totalResults += metrics.resultCount
  }
  const avgDuration = durations.reduce((a, b) => a + b, 0) / durations.length
  return {
    label: scenario.label,
    tags: scenario.tags,
    root: scenario.root,
    avgDurationMs: avgDuration,
    minDurationMs: Math.min(...durations),
    maxDurationMs: Math.max(...durations),
    avgResultCount: totalResults / runs,
  }
}

function main() {
  const start = performance.now()
  const store = buildStore()
  const buildDuration = performance.now() - start

  const scenarios: Scenario[] = [
    { label: 'single-tag + root', tags: ['cat'], root: 'alpha' },
    { label: 'multi-tag + root', tags: ['outdoor', 'nature'], root: 'gamma' },
    { label: 'single-tag global', tags: ['portrait'] },
    { label: 'multi-tag global', tags: ['urban', 'macro'] },
  ]

  const results = scenarios.map((scenario) => runScenario(store, scenario, 10))

  const reportLines = [
    '# Image Filter Benchmark (Synthetic)',
    '',
    `Dataset: ${DATASET_SIZE.toLocaleString()} images`,
    `Tag pool: ${TAG_POOL.length} tags`,
    `Root pool: ${ROOT_POOL.length} roots`,
    `Build duration: ${buildDuration.toFixed(2)} ms`,
    '',
    '| Scenario | Tags | Root | Avg (ms) | Min (ms) | Max (ms) | Avg Results |',
    '| --- | --- | --- | --- | --- | --- | --- |',
    ...results.map(
      (r) =>
        `| ${r.label} | ${r.tags.join(', ')} | ${r.root ?? '—'} | ${r.avgDurationMs.toFixed(
          3,
        )} | ${r.minDurationMs.toFixed(3)} | ${r.maxDurationMs.toFixed(3)} | ${r.avgResultCount.toFixed(0)} |`,
    ),
    '',
    '> Generated by `workstation/scripts/bench-image-filter.ts`',
  ]

  const outputDir = join(__dirname, '..', 'notes', 'benchmark-results')
  mkdirSync(outputDir, { recursive: true })
  const timestamp = new Date().toISOString().replace(/[:.]/g, '-')
  const outputPath = join(outputDir, `${timestamp}.md`)
  writeFileSync(outputPath, reportLines.join('\n'))

  console.log(`Benchmark report written to ${outputPath}`)
}

main()
